### ISSUE TITLE
add error catching routes

### ISSUE THREAD

**Issue by MrCookiefries** [chingu-voyages/v40-bears-team-33bd#11]
# Explanation
App just has routes, there should be a catch all route for any errors that may arise during a route. Using the next function with the error, we can be sure the error handler route is hit with the appropriate error.

Addiontially, when an unknown route is hit, a 404 error should arise & go to the catch all, instead of a generic 500 internal server error cryptic message.

# Tasks

- [x] Create a 404 not found error route to call next & pass the error with it
- [x] Create a catch all error handler route to deal with all route errors passed with next
- [x] Create a custom express error to take an error message with an error code status number
